[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Omit public keys from secrets scanning as they are expected to be embedded in the build
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_BASE_URL"
